#pragma once

#include <openmedia/byte.h>

OM_ENUM(OMContainerId, uint32_t) {
  OM_CONTAINER_NONE = 0,

  // Universal containers
  OM_CONTAINER_MKV = OM_MAGIC_RAW(0x1A, 0x45, 0xDF, 0xA3),
  OM_CONTAINER_MP4 = OM_MAGIC('MP4 '),
  OM_CONTAINER_MOV = OM_MAGIC('MOV '),
  OM_CONTAINER_OGG = OM_MAGIC('OggS'),
  OM_CONTAINER_AVI = OM_MAGIC('AVI '),
  OM_CONTAINER_WEBM = OM_MAGIC('webm'),
  OM_CONTAINER_ASF = OM_MAGIC_RAW(0x30, 0x26, 0xB2, 0x75),
  OM_CONTAINER_NUT = OM_MAGIC('NUTS'),

  // Transport/Program streams
  OM_CONTAINER_MPEG_TS = OM_MAGIC('MPTS'),
  OM_CONTAINER_MPEG_PS = OM_MAGIC('MPPS'),
  OM_CONTAINER_FLV = OM_MAGIC_RAW('F', 'L', 'V', 0x01),

  // Audio containers
  OM_CONTAINER_WAV = OM_MAGIC('WAVE'),
  OM_CONTAINER_WAVE64 = OM_MAGIC('W64f'),
  OM_CONTAINER_MP3 = OM_MAGIC('.mp2'),
  OM_CONTAINER_M4A = OM_MAGIC('m4af'),
  OM_CONTAINER_FLAC = OM_MAGIC('fLaC'),
  OM_CONTAINER_APE = OM_MAGIC('Mac '),

  // Image containers
  OM_CONTAINER_JPEG = OM_MAGIC('JPEG'), // JFIF/EXIF
  OM_CONTAINER_PNG = OM_MAGIC_RAW(0x89, 'P', 'N', 'G'),
  OM_CONTAINER_TIFF = OM_MAGIC('II42'),
  OM_CONTAINER_GIF = OM_MAGIC('GIF8'),
  OM_CONTAINER_WEBP = OM_MAGIC('WEBP'),
  OM_CONTAINER_HEIF = OM_MAGIC('HEIF'), // HEIC/AVIF
  OM_CONTAINER_ICO = OM_MAGIC('ico '),
  OM_CONTAINER_ICNS = OM_MAGIC('icns'),
  OM_CONTAINER_EXR = OM_MAGIC_RAW(0x76, 0x2F, 0x31, 0x01),
  OM_CONTAINER_BMP = OM_MAGIC_RAW('B', 'M', 0x00, 0x00),
  OM_CONTAINER_TGA = OM_MAGIC('TGA '),
};
